<a href="https://colab.research.google.com/github/JuanAToroA/IA---2025/blob/main/lab_01_01_practice_submission.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LAB 01.01 - Practice submission

In [ ]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/ai4eng.v1/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()


replicating local resources


In [ ]:
import inspect
from local.lib.rlxmoocapi import session
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L01.01", varname="student");

logging in as jandres.toro1@udea.edu.co... please wait

-------------
using course session ai4eng.v1.udea.r3::2025.1
success!! you are logged in
-------------


### Ejercicio 1: Suma dos matrices

Completa la función `suma_matrices` para que, dadas dos arrays numpy cualquiera devuelva la suma elemento a elemento.

#### Ejemplo de ejecución

    > s = np.array([1,2,3])
    > t = np.array([4,5,6])
    > suma_matrices(s,t)
    
      [5 7 9]
     
_Sugerencia_: completa el código de la siguiente manera:

    def suma_matrices(a,b):
       ## --- TU CODIGO AQUI ---
       result = a + b
       return result

In [ ]:

def suma_matrices(a,b):
    ## --- TU CODIGO AQUI ---
    result = a + b
    return result



comprueba manualmente tu código

In [ ]:
import numpy as np
a = np.random.randint(10, size=(3,2))
b = np.random.randint(10, size=(3,2))
print (a)
print (b)
print (suma_matrices(a,b))

[[2 1]
 [5 2]
 [9 9]]
[[6 9]
 [1 0]
 [3 2]]
[[ 8 10]
 [ 6  2]
 [12 11]]


#### registra tu solución en línea

In [ ]:
student.submit_task(globals(), task_id="task_01");

error: end_date (set session.debug=True for tracebacks)

### Ejercicio 2: Realiza un cálculo

En este ejercicio, al ejecutar la celda de más abajo, se generará una lista de número aleatorios.

Tendrás que calcular el valor promedio de la lista y asignarlo a la variable `avg` más abajo.

Puedes usar el método que quieras para realizar el cálculo (a mano, excel, python, etc.) lo que importa es el valor que obtengas.


In [ ]:
import numpy as np
rlist = np.random.randint(100, size=10)
rlist

array([94, 71, 82,  7, 70, 53, 42,  0, 78, 33])

#### tu solución

In [ ]:
avg = np.mean(rlist)
print(avg)


53.0


#### registra tu solución en línea

In [ ]:
student.submit_task(globals(), task_id="task_02");

error: end_date (set session.debug=True for tracebacks)